### ISSUE TITLE
Failed to connect to the host via ssh: ssh: connect to host x.y.x.a port 22: Operation timed out"

### ISSUE THREAD

**Issue by bwearp** [qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules#13]
Hello,

Is the below incorrect?

Playbook:
---
- hosts: my_vmware_pro
  gather_facts: no
  collections:
    - qsypoq.vmware_desktop
  tasks:

  - name: "List all VMs"
    win_vmware_desktop_vminfos:
      username: "john.smith"
      password: "password1234"
      api_url: "http://192.168.1.0.1"
      api_port: "8697"
      validate_certs: no

Inventory file:

[VMWare_Servers]
my_vmware_pro ansible_host=192.168.10.1 api-username="john.smith" api-password="password1234" api_url="http://192.168.10.1" api_port="8697"

Command:
ansible-playbook -i hosts.yml vmware_desktop.yml -vvv

[john]% ansible-playbook -i hosts.yml vmware_desktop.yml -vvv
ansible-playbook 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/john/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible-playbook
  python version = 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /Volumes/Dropbox/Ansible/VMWare/hosts.yml as it did not pass its verify_file() method
Parsed /Volumes/Dropbox/Ansible/VMWare/hosts.yml inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: vmware_desktop.yml ********************************************************************************************************************************************************************************************************************************************************************************************
1 plays in vmware_desktop.yml

PLAY [my_vmware_pro] ****************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [List all VMs] *****************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Volumes/Dropbox/Ansible/VMWare/vmware_desktop.yml:8
<192.168.10.1> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.10.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/john/.ansible/cp/82c0ac9e26 192.168.10.1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.10.1> (255, b'', b'ssh: connect to host 192.168.10.1 port 22: Operation timed out\r\n')
fatal: [my_vmware_pro]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: ssh: connect to host 192.168.10.1 port 22: Operation timed out",
    "unreachable": true
}

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************
my_vmware_pro              : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0

**Comment by bwearp** [comment]
SOLUTION: make sure to make the connection local. 

inventory: ansible_connection=local
playbook task: delegate_to: localhost

**Comment by qsypoq** [comment]
Auto-resolved
