### ISSUE TITLE
MODULE FAILURE\nSee stdout/stderr for the exact error 

### ISSUE THREAD

**Issue by bwearp** [qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules#14]
[john]% ansible-playbook -i hosts.yml vmware_desktop.yml -vvv -M ./modules
ansible-playbook 2.10.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/john/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible-playbook
  python version = 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) [Clang 6.0 (clang-600.0.57)]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /Volumes/Dropbox/Ansible/VMWare/hosts.yml as it did not pass its verify_file() method
Parsed /Volumes/Dropbox/Ansible/VMWare/hosts.yml inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: vmware_desktop.yml ********************************************************************************************************************************************************************************************************************************************************************************************
1 plays in vmware_desktop.yml

PLAY [my_vmware_pro] ****************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [List all VMs] *****************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Volumes/Dropbox/Ansible/VMWare/vmware_desktop.yml:8
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: john
<127.0.0.1> EXEC /bin/sh -c 'echo ~john && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/john/.ansible/tmp `"&& mkdir "` echo /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158 `" && echo ansible-tmp-1624978848.1419132-5504-211548254995158="` echo /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158 `" ) && sleep 0'
Using module file /Users/john/.ansible/collections/ansible_collections/qsypoq/vmware_desktop/plugins/modules/win_vmware_desktop_vminfos.py
<127.0.0.1> PUT /Users/john/.ansible/tmp/ansible-local-5499fkq0_mfh/tmp2melr67b TO /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/AnsiballZ_win_vmware_desktop_vminfos.py
<127.0.0.1> PUT /Users/john/.ansible/tmp/ansible-local-5499fkq0_mfh/tmpzywbxi1f TO /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/args
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/ /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/AnsiballZ_win_vmware_desktop_vminfos.py /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/args && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/AnsiballZ_win_vmware_desktop_vminfos.py /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/args && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/john/.ansible/tmp/ansible-tmp-1624978848.1419132-5504-211548254995158/ > /dev/null 2>&1 && sleep 0'
fatal: [my_vmware_pro]: FAILED! => {
    "changed": false,
    "module_stderr": "",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0
}

**Comment by qsypoq** [comment]
Hi, if this is still an issue can you provide the playbook your are trying to run ? Thanks.
