### ISSUE TITLE
Linux - VMs can't be cloned Error 409

### ISSUE THREAD

**Issue by ManuGithubSteam** [qsypoq/Ansible-VMware-Workstation-Fusion-Pro-Modules#7]
Hi
This is my setup Arch linux:

localhost
- runs ansible
- runs vmware workstation 

Goal:
Clone "AnTemp" VM (really long id - see below) to an new VM and give the VM a new hostname.

Problem:
- Cloneing does not work.

When i try to use the "clone VMs" the connection suceeds but none of my VMs cloned. Instead i recive:

`
manuel@R920:~/.ansible$ansible-playbook -i hosts an_clone_vm_loadb.yml -vvv
ansible-playbook 2.10.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/manuel/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.6 (default, Sep 30 2020, 04:00:38) [GCC 10.2.0]
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/manuel/.ansible/hosts as it did not pass its verify_file() method
script declined parsing /home/manuel/.ansible/hosts as it did not pass its verify_file() method
auto declined parsing /home/manuel/.ansible/hosts as it did not pass its verify_file() method
Parsed /home/manuel/.ansible/hosts inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: an_clone_vm_loadb.yml ***************************************************************************************************************************************************************************************************************************************
1 plays in an_clone_vm_loadb.yml

PLAY [localhost] ******************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Clone] **********************************************************************************************************************************************************************************************************************************************************
task path: /home/manuel/.ansible/an_clone_vm_loadb.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: manuel
<localhost> EXEC /bin/sh -c 'echo ~manuel && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/manuel/.ansible/tmp `"&& mkdir "` echo /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385 `" && echo ansible-tmp-1606252755.303682-106025-67445614140385="` echo /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385 `" ) && sleep 0'
<localhost> Attempting python interpreter discovery
<localhost> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<localhost> Python interpreter discovery fallback (unable to get Linux distribution/version info)
Using module file /home/manuel/.ansible/collections/ansible_collections/qsypoq/vmware_desktop/plugins/modules/unix_vmware_desktop_vmmgmt.py
<localhost> PUT /home/manuel/.ansible/tmp/ansible-local-1060167k_pq3u1/tmpgo0jvcm5 TO /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385/AnsiballZ_unix_vmware_desktop_vmmgmt.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385/ /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385/AnsiballZ_unix_vmware_desktop_vmmgmt.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385/AnsiballZ_unix_vmware_desktop_vmmgmt.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/manuel/.ansible/tmp/ansible-tmp-1606252755.303682-106025-67445614140385/ > /dev/null 2>&1 && sleep 0'
[WARNING]: Module did not set no_log for password
[WARNING]: Platform linux on host localhost is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change the meaning of that path. See
https://docs.ansible.com/ansible/2.10/reference_appendices/interpreter_discovery.html for more information.
fatal: [localhost]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "clone",
            "api_port": "8697",
            "api_url": "http://127.0.0.1",
            "memory_mb": null,
            "name": "An-LoadBalancer",
            "num_cpus": null,
            "password": "Ansible123#",
            "target_vm": "P6VIGOQK5E0RBNAU61C7DQFQFKFBPLE9",
            "target_vm_name": "",
            "timeout": 30,
            "username": "ansible",
            "validate_certs": false
        }
    },
    "msg": "HTTP Error 409: Conflict"
}

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
`

my host file:

[controller]
ans-control ansible_connection=local

[local]
localhost ansible_connection=local

[loadbalancer]
lb01 ansible_user=ansible

[webserver]
app01 ansible_user=ansible
app02 ansible_user=ansible

vmrest ist running as user manuel on the machine. If i run it as root it can not be accessed by ansible i think. (I get no ouput from the list all VMs playbook)

The vmlist plaxbook works and i get my machine ids.

My playbook in question (not working).

`                                                                                                                     
- hosts: localhost
  gather_facts: no
  collections:
    - qsypoq.vmware_desktop
  tasks:

  - name: "Clone"
    unix_vmware_desktop_vmmgmt:
      target_vm: "P6VIGOQK5E0RBNAU61C7DQFQFKFBPLE9"
      action: clone
      name: "An-LoadBalancer"
      username: "ansible"
      password: "Ansible123#"
`

Here the target_vm should be cloneded to the new one with the name An-Load-Balancer. Can i also change the Hostname of the machine while cloning ?

Working:
`
- hosts: localhost
  gather_facts: no
  collections:
    - qsypoq.vmware_desktop
  tasks:

  - name: "List all VMs"
    unix_vmware_desktop_vminfos:
      username: "ansible"
      password: "Ansible123#"
`

Why does this error occur and how can i fix it ?
Thanks!

**Comment by qsypoq** [comment]
Hi, first time encountering this error so we need to dig into your setup.
What was the state of the VM while attempting to clone it ? Because you can't clone a running VM.

Also for hostname edit, did you mean the GUI's name ? Yes you can change it while it's clonning:
AFAIK the GUI's name is only a line the vmx file so if the process is not actualy cloning this exact file (it weight like 4ko, very unlikely) you are good to go. Tested it myself without issue.

**Comment by ManuGithubSteam** [comment]
Hi 
Thanks for the quick response :-) Tried it out and This is the result:

I had two issues:
- The VM was running. Stopping the template VM fixed this.
- Command would timeout. Setting "timeout" fixxed it.

So the original issue here is closed.
However i would like to know why i can not run vmrest as root and ansible as user. If i do this ansible can not connect fully to the rest API and the calls are all empty ? 

At the moment i do not need to add new network interfaces but it would be good to know :-)
Thanks

**Comment by qsypoq** [comment]
vmrest need to be run with the user who use the ressources you want to interact with.

So, if you want to interact with VMs using the root account, you need to launch Workstation as root and add the VMs in this view. Not recommended because you can have conflicts like this:
![image](https://user-images.githubusercontent.com/15003491/100651545-e4d73080-3345-11eb-9301-370d77a5116f.png)

AFAIK this is the only actual way to manage VMs + networks without alternating vmrest launchs.
Still, one can write a playbook with tasks restarting vmrest with the desired user before making the actions ? Would be great 😄
